[project]
name = "gen-ai-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-ollama>=1.0.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
